### ISSUE TITLE
Cloud cover 33:

### ISSUE THREAD

**Issue by ghost** [kareey-commits/digital-clock#1]
Hey Susan, I need to know you ... Are you from MMUST or Rongo.....

**Comment by Susan-Wangari** [comment]
Rongo

**Comment by ghost** [comment]
Great.... I'm from MMUST , there one platform that unite developers from
the Universities around.... I've never been exposed to one in MMUST

**Comment by Susan-Wangari** [comment]
maybe developer student clubs or google developer groups western

**Comment by ghost** [comment]
Cool... Thanks for that... I know one day we will meet.

**Comment by Susan-Wangari** [comment]
resolved
